### ISSUE TITLE
Buggg

### ISSUE THREAD

**Issue by Angize** [NidukaAkalanka/x-ui-english#133]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Screenshot_2023-01-30-11-24-49-641_com sonelli juicessh](https://user-images.githubusercontent.com/51332955/215420539-2f52c2d3-1cba-4664-bddc-a8bb1f33202e.jpg)
 
-.- check please

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @Angize !

In the log, you are getting `UNIQUE constraint failed` because you are using a string which is duplicated or previously used for the Email section. Please use the loop icon beside that to generate a unique fake email so you won't get this error. Please figure out for which client you did the above mistake and delete that.
