### ISSUE TITLE
diffrence in traffics counts

### ISSUE THREAD

**Issue by mkmmh1073** [NidukaAkalanka/x-ui-english#160]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello; Thanks for such a great panel 
I wonder why there is difference between the inbounds traffic and the total traffic shown in system status?

![traffic-used](https://user-images.githubusercontent.com/126575096/221853152-468548d3-1426-45b9-8e01-165ca95ab411.PNG)

![overal-traffic](https://user-images.githubusercontent.com/126575096/221853196-0791fdfc-9530-43fe-9060-69b1388d27c8.PNG)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by saeedtntt** [comment]
I run the database file on another server, but the amount of traffic consumed by each user is always zero and does not change after use.
0 B / 0 B

**Comment by NidukaAkalanka** [comment]
In tbe first attachment's total traffic means the upload + download traffic consumed by v2ray inbounds. In the second attachment, the total traffic consumed by the server since the startup is what's being displayed. Normally, a server consumes traffic not only for your v2rays. It consumes traffic for many other processes such as system updates, status reporting to the server provider, etc and etc. This isn't an issue but total default
