### ISSUE TITLE
Problem in displaying the amount of user traffic

### ISSUE THREAD

**Issue by saeedtntt** [NidukaAkalanka/x-ui-english#167]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I run the database file on another server, but the amount of traffic consumed by each user is always zero and does not change after use.
0 B / 0 B
![sss](https://user-images.githubusercontent.com/49751332/222923088-01fe060b-5732-42fa-b6a7-3dc65138ad39.jpg)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Benyormin** [comment]
I have the same problem

**Comment by hrmshams** [comment]
any update? i have the same problem! 

i can't even add a log file address to v2ray config (it resets the config after reloading the x-ui)

**Comment by sohrabp72** [comment]
same problem with fresh installation, database is not moved, absolutely fresh. still the problem with no traffic.

**Comment by NidukaAkalanka** [comment]
I didn't get the part where you said you are running database file on another server. But I do get undoubtedly is that, all the users in the above screenshots would not work because they are incomplete. You haven't type/generated an email for the users. That filed is blank. So, 0/0 is the default behavior. How an inbound which isn't working output a traffic count? After all, the specific features works perfectly on a fresh installation with everything complete in the config.
