### ISSUE TITLE
No traffic limit

### ISSUE THREAD

**Issue by sohrabp72** [NidukaAkalanka/x-ui-english#193]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

no traffic limit.
even after 3days, still no traffic count.

### Version of x-ui

<details>

```console
$ x-ui version
# 0.2.1.2
```

</details>

### x-ui log or xray log

<details>

```console
# asd
```

</details>

**Comment by NidukaAkalanka** [comment]
Traffic count do works as well as the traffic limiter. The issue is not globle but individual which is likely to occured due to any error in configuration or installation by yourself. With neither the x ui log nor a detaild description, I can no longer elaborate. Once again, the features that you said to be not working do work seemlessly
