### ISSUE TITLE
QR Code doesn't return domain

### ISSUE THREAD

**Issue by Ariojavand** [NidukaAkalanka/x-ui-english#50]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi
when i click on Operate > Qrcode
its returns ip as address field instead of Domain name!
any solution?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @Ariojavand !

Could you please elaborate a bit more? For which type of v2ray configs did you face this? If it is TLS enabled, use your domain name instead of thr ip in the TLS domain name. 

However in some countries, like Sri Lanka, it is recommended to use the ip instead of the domain name to connect directly without requesting name resolutions from thr isp
