### ISSUE TITLE
IP limit not working behind cloudflare

### ISSUE THREAD

**Issue by amirpiri** [NidukaAkalanka/x-ui-english#61]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

IP limit not working when behind a CDN, I think your code only gets CDN ip address. You should check X-Forwarded-For to get client real IP address.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @amirpiri !

This isn't really an issue because all the clients will get the CDN ip address. It will work flawlessly without a CDN. Tagged as duplicated as there were many issues opened regarding this. 

However, if you know any method to resolve this, (Asking for I didn't get what's X-Forwarded-For means) please consider contributing or commenting down the way of doing that at https://github.com/NidukaAkalanka/x-ui-english/discussions/68
